# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CodeRepositoryV1(BaseModel):
    """
    Code repository integration (GitHub PAT only). Stores the token; repo URL is set per component. The PAT must have read access to the repositories you want to connect. 
    """ # noqa: E501
    type: StrictStr
    flavour: StrictStr
    pat: Annotated[str, Field(min_length=1, strict=True)] = Field(description="GitHub Personal Access Token used to access repository contents. NOTE: For classic PATs, grant the `repo` scope (read access). For fine-grained PATs, grant `Contents: Read-only` permission. ")
    __properties: ClassVar[List[str]] = ["type", "flavour", "pat"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['REPOSITORY']):
            raise ValueError("must be one of enum values ('REPOSITORY')")
        return value

    @field_validator('flavour')
    def flavour_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['GIT']):
            raise ValueError("must be one of enum values ('GIT')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CodeRepositoryV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CodeRepositoryV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "flavour": obj.get("flavour"),
            "pat": obj.get("pat")
        })
        return _obj


