# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from .log_source_auth_mechanism_v1 import LogSourceAuthMechanismV1
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JaegerV1(BaseModel):
    """
    Jaeger distributed tracing backend.
    """ # noqa: E501
    type: StrictStr
    flavour: StrictStr
    url: StrictStr = Field(description="Jaeger query API base URL.", json_schema_extra={"examples": ["http://localhost:16686"]})
    auth_mechanism: Optional[LogSourceAuthMechanismV1] = None
    __properties: ClassVar[List[str]] = ["type", "flavour", "url", "auth_mechanism"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['TRACE_SOURCE']):
            raise ValueError("must be one of enum values ('TRACE_SOURCE')")
        return value

    @field_validator('flavour')
    def flavour_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['JAEGER']):
            raise ValueError("must be one of enum values ('JAEGER')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JaegerV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of auth_mechanism
        if self.auth_mechanism:
            _dict['auth_mechanism'] = self.auth_mechanism.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JaegerV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "flavour": obj.get("flavour"),
            "url": obj.get("url"),
            "auth_mechanism": LogSourceAuthMechanismV1.from_dict(obj["auth_mechanism"]) if obj.get("auth_mechanism") is not None else None
        })
        return _obj


