# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from .click_house_v1 import ClickHouseV1
from .loki_v1 import LokiV1
from .open_search_v1 import OpenSearchV1
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

LOGSOURCEV1_ONE_OF_SCHEMAS = ["ClickHouseV1", "LokiV1", "OpenSearchV1"]

class LogSourceV1(BaseModel):
    """
    Log aggregator is a service that aggregates logs.
    """
    # data type: LokiV1
    oneof_schema_1_validator: Optional[LokiV1] = None
    # data type: OpenSearchV1
    oneof_schema_2_validator: Optional[OpenSearchV1] = None
    # data type: ClickHouseV1
    oneof_schema_3_validator: Optional[ClickHouseV1] = None
    actual_instance: Optional[Union[ClickHouseV1, LokiV1, OpenSearchV1]] = None
    one_of_schemas: Set[str] = { "ClickHouseV1", "LokiV1", "OpenSearchV1" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = LogSourceV1.model_construct()
        error_messages = []
        match = 0
        # validate data type: LokiV1
        if not isinstance(v, LokiV1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LokiV1`")
        else:
            match += 1
        # validate data type: OpenSearchV1
        if not isinstance(v, OpenSearchV1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OpenSearchV1`")
        else:
            match += 1
        # validate data type: ClickHouseV1
        if not isinstance(v, ClickHouseV1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ClickHouseV1`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in LogSourceV1 with oneOf schemas: ClickHouseV1, LokiV1, OpenSearchV1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in LogSourceV1 with oneOf schemas: ClickHouseV1, LokiV1, OpenSearchV1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into LokiV1
        try:
            instance.actual_instance = LokiV1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into OpenSearchV1
        try:
            instance.actual_instance = OpenSearchV1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ClickHouseV1
        try:
            instance.actual_instance = ClickHouseV1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into LogSourceV1 with oneOf schemas: ClickHouseV1, LokiV1, OpenSearchV1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into LogSourceV1 with oneOf schemas: ClickHouseV1, LokiV1, OpenSearchV1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ClickHouseV1, LokiV1, OpenSearchV1]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


