# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from .log_source_auth_api_key_v1 import LogSourceAuthAPIKeyV1
from .log_source_auth_basic_v1 import LogSourceAuthBasicV1
from .log_source_auth_bearer_v1 import LogSourceAuthBearerV1
from .log_source_auth_o_auth_v1 import LogSourceAuthOAuthV1
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class LogSourceAuthMechanismV1(BaseModel):
    """
    Authentication for log/trace sources (at most one mechanism; same structure as RCA engine AuthMechanism).
    """ # noqa: E501
    basic: Optional[LogSourceAuthBasicV1] = None
    bearer: Optional[LogSourceAuthBearerV1] = None
    oauth: Optional[LogSourceAuthOAuthV1] = None
    api_key: Optional[LogSourceAuthAPIKeyV1] = None
    __properties: ClassVar[List[str]] = ["basic", "bearer", "oauth", "api_key"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LogSourceAuthMechanismV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of basic
        if self.basic:
            _dict['basic'] = self.basic.to_dict()
        # override the default output from pydantic by calling `to_dict()` of bearer
        if self.bearer:
            _dict['bearer'] = self.bearer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of oauth
        if self.oauth:
            _dict['oauth'] = self.oauth.to_dict()
        # override the default output from pydantic by calling `to_dict()` of api_key
        if self.api_key:
            _dict['api_key'] = self.api_key.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LogSourceAuthMechanismV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "basic": LogSourceAuthBasicV1.from_dict(obj["basic"]) if obj.get("basic") is not None else None,
            "bearer": LogSourceAuthBearerV1.from_dict(obj["bearer"]) if obj.get("bearer") is not None else None,
            "oauth": LogSourceAuthOAuthV1.from_dict(obj["oauth"]) if obj.get("oauth") is not None else None,
            "api_key": LogSourceAuthAPIKeyV1.from_dict(obj["api_key"]) if obj.get("api_key") is not None else None
        })
        return _obj


