# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class McpServerV1(BaseModel):
    """
    MCP server integration (stdio, SSE, or Streamable HTTP).
    """ # noqa: E501
    type: StrictStr
    flavour: StrictStr = Field(description="Stable name used to reference this server from skill mcp_servers lists. Examples: GITHUB, JIRA, CUSTOM_MCP. ", json_schema_extra={"examples": ["GITHUB"]})
    transport: StrictStr
    url: Optional[StrictStr] = Field(default=None, description="Required for sse and streamable_http transports.", json_schema_extra={"examples": ["https://api.githubcopilot.com/mcp/"]})
    command: Optional[StrictStr] = Field(default=None, description="Required for stdio transport.")
    args: Optional[List[StrictStr]] = None
    env: Optional[Dict[str, StrictStr]] = None
    headers: Optional[Dict[str, StrictStr]] = None
    timeout: Optional[Union[StrictFloat, StrictInt]] = None
    sse_read_timeout: Optional[Union[StrictFloat, StrictInt]] = None
    cache_tools_list: Optional[StrictBool] = False
    __properties: ClassVar[List[str]] = ["type", "flavour", "transport", "url", "command", "args", "env", "headers", "timeout", "sse_read_timeout", "cache_tools_list"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['MCP']):
            raise ValueError("must be one of enum values ('MCP')")
        return value

    @field_validator('transport')
    def transport_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['stdio', 'sse', 'streamable_http']):
            raise ValueError("must be one of enum values ('stdio', 'sse', 'streamable_http')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of McpServerV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of McpServerV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "flavour": obj.get("flavour"),
            "transport": obj.get("transport"),
            "url": obj.get("url"),
            "command": obj.get("command"),
            "args": obj.get("args"),
            "env": obj.get("env"),
            "headers": obj.get("headers"),
            "timeout": obj.get("timeout"),
            "sse_read_timeout": obj.get("sse_read_timeout"),
            "cache_tools_list": obj.get("cache_tools_list") if obj.get("cache_tools_list") is not None else False
        })
        return _obj


