# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Page(BaseModel):
    """
    Page
    """ # noqa: E501
    total: StrictInt = Field(description="Total number of contents", json_schema_extra={"examples": [100]})
    page: StrictInt = Field(description="Page number", json_schema_extra={"examples": [0]})
    size: StrictInt = Field(description="Page size", json_schema_extra={"examples": [10]})
    total_pages: StrictInt = Field(description="Total number of pages", json_schema_extra={"examples": [10]})
    has_more: Optional[StrictBool] = Field(default=None, description="Whether there are more pages", json_schema_extra={"examples": [True]})
    is_first: Optional[StrictBool] = Field(default=None, description="Whether this is the first page", json_schema_extra={"examples": [True]})
    is_last: Optional[StrictBool] = Field(default=None, description="Whether this is the last page", json_schema_extra={"examples": [True]})
    __properties: ClassVar[List[str]] = ["total", "page", "size", "total_pages", "has_more", "is_first", "is_last"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Page from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Page from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total": obj.get("total"),
            "page": obj.get("page"),
            "size": obj.get("size"),
            "total_pages": obj.get("total_pages"),
            "has_more": obj.get("has_more"),
            "is_first": obj.get("is_first"),
            "is_last": obj.get("is_last")
        })
        return _obj


