# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SkillStepResource(BaseModel):
    """
    SkillStepResource
    """ # noqa: E501
    id: StrictStr
    type: StrictStr
    skill_id: Optional[StrictStr] = None
    tool_id: Optional[StrictStr] = None
    objective: StrictStr
    params: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "type", "skill_id", "tool_id", "objective", "params"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['invoke_skill', 'invoke_tool', 'synthesize']):
            raise ValueError("must be one of enum values ('invoke_skill', 'invoke_tool', 'synthesize')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SkillStepResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if skill_id (nullable) is None
        # and model_fields_set contains the field
        if self.skill_id is None and "skill_id" in self.model_fields_set:
            _dict['skill_id'] = None

        # set to None if tool_id (nullable) is None
        # and model_fields_set contains the field
        if self.tool_id is None and "tool_id" in self.model_fields_set:
            _dict['tool_id'] = None

        # set to None if params (nullable) is None
        # and model_fields_set contains the field
        if self.params is None and "params" in self.model_fields_set:
            _dict['params'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SkillStepResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "skill_id": obj.get("skill_id"),
            "tool_id": obj.get("tool_id"),
            "objective": obj.get("objective"),
            "params": obj.get("params")
        })
        return _obj


