# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from .skill_step_resource import SkillStepResource
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SkillResource(BaseModel):
    """
    SkillResource
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    description: StrictStr
    instructions: StrictStr
    kind: Optional[StrictStr] = 'simple'
    capabilities: Optional[List[StrictStr]] = None
    mcp_servers: Optional[List[StrictStr]] = None
    steps: Optional[List[SkillStepResource]] = None
    model: Optional[StrictStr] = 'gpt-5.1'
    input_schema: Optional[Dict[str, Any]] = None
    output_schema: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "description", "instructions", "kind", "capabilities", "mcp_servers", "steps", "model", "input_schema", "output_schema"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['simple', 'composed']):
            raise ValueError("must be one of enum values ('simple', 'composed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SkillResource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in steps (list)
        _items = []
        if self.steps:
            for _item_steps in self.steps:
                if _item_steps:
                    _items.append(_item_steps.to_dict())
            _dict['steps'] = _items
        # set to None if input_schema (nullable) is None
        # and model_fields_set contains the field
        if self.input_schema is None and "input_schema" in self.model_fields_set:
            _dict['input_schema'] = None

        # set to None if output_schema (nullable) is None
        # and model_fields_set contains the field
        if self.output_schema is None and "output_schema" in self.model_fields_set:
            _dict['output_schema'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SkillResource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "instructions": obj.get("instructions") if obj.get("instructions") is not None else '',
            "kind": obj.get("kind") if obj.get("kind") is not None else 'simple',
            "capabilities": obj.get("capabilities"),
            "mcp_servers": obj.get("mcp_servers"),
            "steps": [SkillStepResource.from_dict(_item) for _item in obj["steps"]] if obj.get("steps") is not None else None,
            "model": obj.get("model") if obj.get("model") is not None else 'gpt-5.1',
            "input_schema": obj.get("input_schema"),
            "output_schema": obj.get("output_schema")
        })
        return _obj


