# coding: utf-8

"""
    Weave Orchestrator API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from .code_repository_v1 import CodeRepositoryV1
from .log_source_v1 import LogSourceV1
from .mcp_server_v1 import McpServerV1
from .trace_source_v1 import TraceSourceV1
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

TENANTINTEGRATIONV1_ONE_OF_SCHEMAS = ["CodeRepositoryV1", "LogSourceV1", "McpServerV1", "TraceSourceV1"]

class TenantIntegrationV1(BaseModel):
    """
    Tenant integration is a configuration for a tenant integration.
    """
    # data type: LogSourceV1
    oneof_schema_1_validator: Optional[LogSourceV1] = None
    # data type: CodeRepositoryV1
    oneof_schema_2_validator: Optional[CodeRepositoryV1] = None
    # data type: TraceSourceV1
    oneof_schema_3_validator: Optional[TraceSourceV1] = None
    # data type: McpServerV1
    oneof_schema_4_validator: Optional[McpServerV1] = None
    actual_instance: Optional[Union[CodeRepositoryV1, LogSourceV1, McpServerV1, TraceSourceV1]] = None
    one_of_schemas: Set[str] = { "CodeRepositoryV1", "LogSourceV1", "McpServerV1", "TraceSourceV1" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = TenantIntegrationV1.model_construct()
        error_messages = []
        match = 0
        # validate data type: LogSourceV1
        if not isinstance(v, LogSourceV1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `LogSourceV1`")
        else:
            match += 1
        # validate data type: CodeRepositoryV1
        if not isinstance(v, CodeRepositoryV1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CodeRepositoryV1`")
        else:
            match += 1
        # validate data type: TraceSourceV1
        if not isinstance(v, TraceSourceV1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `TraceSourceV1`")
        else:
            match += 1
        # validate data type: McpServerV1
        if not isinstance(v, McpServerV1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `McpServerV1`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in TenantIntegrationV1 with oneOf schemas: CodeRepositoryV1, LogSourceV1, McpServerV1, TraceSourceV1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in TenantIntegrationV1 with oneOf schemas: CodeRepositoryV1, LogSourceV1, McpServerV1, TraceSourceV1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into LogSourceV1
        try:
            instance.actual_instance = LogSourceV1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CodeRepositoryV1
        try:
            instance.actual_instance = CodeRepositoryV1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into TraceSourceV1
        try:
            instance.actual_instance = TraceSourceV1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into McpServerV1
        try:
            instance.actual_instance = McpServerV1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into TenantIntegrationV1 with oneOf schemas: CodeRepositoryV1, LogSourceV1, McpServerV1, TraceSourceV1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into TenantIntegrationV1 with oneOf schemas: CodeRepositoryV1, LogSourceV1, McpServerV1, TraceSourceV1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CodeRepositoryV1, LogSourceV1, McpServerV1, TraceSourceV1]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


